# Generated by Django 2.2 on 2021-08-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_commenter_app', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
